version: "3.9"

services:
  node_server:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
      MONGODB_URI: mongodb://mongodb:27017/interview_ai
      FACE_ANALYZER_URL: http://face_analyzer:8001
      VOICE_ANALYZER_URL: http://voice_analyzer:8002
      WHISPER_SERVICE_URL: http://whisper_service:8003
      
    volumes:
      - .:/app
      - ./tmp:/tmp
    depends_on:
      - redis
      - mongodb

  worker:
    build: .
    command: node --loader ts-node/esm src/jobs/index.ts
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
      MONGODB_URI: mongodb://mongodb:27017/interview_ai
      FACE_ANALYZER_URL: http://face_analyzer:8001
      VOICE_ANALYZER_URL: http://voice_analyzer:8002
      WHISPER_SERVICE_URL: http://whisper_service:8003
    volumes:
      - .:/app
      - ./tmp:/tmp
    depends_on:
      - redis
      - mongodb
      - node_server

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  face_analyzer:
    build: ./ai_services/face_analyzer
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    volumes:
      - ./tmp:/tmp
    environment:
      PYTHONUNBUFFERED: 1
      PORT: 8001
  face_analyzer_worker:
    build: ./ai_services/face_analyzer
    command: python worker.py
    working_dir: /app
    depends_on: [redis, face_analyzer]
    volumes:
    - ./tmp:/tmp

  voice_analyzer:
    build: ./ai_services/voice_analyzer
    command: uvicorn main:app --host 0.0.0.0 --port 8002
    ports:
      - "8002:8002"
    volumes:
      - ./tmp:/tmp
    environment:
      PYTHONUNBUFFERED: 1
      PORT: 8002
  voice_analyzer_worker:
    build: ./ai_services/voice_analyzer
    command: python worker.py
    working_dir: /app
    depends_on: [redis, voice_analyzer]
    volumes:
    - ./tmp:/tmp
  # whisper_service:
  #   build: ./ai_services/whisper_service
  #   command: uvicorn main:app --host 0.0.0.0 --port 8003
  #   ports:
  #     - "8003:8003"
  #   volumes:
  #     - ./tmp:/tmp
  #   environment:
  #     PYTHONUNBUFFERED: 1
  #     PORT: 8003

volumes:
  redis_data:
  mongodb_data:
